
export const NOT_AUTHORIZED_TO_EDIT_DOCUMENT = 'Du hast nicht die Berechtigung dieses Dokument zu bearbeiten.';
export const NOT_AUTHORIZED_TO_EDIT_DOCUMENT_EDITORS = 'Du hast nicht die Berechtigung die Bearbeiter dieses Dokuments zu bearbeiten.';
export const NOT_AUTHORIZED_TO_RESTORE_DOCUMENT = 'Du hast nicht die Berechtigung dieses Dokument zu wiederherzustellen.';
export const NOT_AUTHORIZED_TO_DELETE_ROOM = 'Du hast nicht die Berechtigung diesen Raum zu löschen.';
export const USER_ALREADY_EXISTS = 'Ein Benutzer mit dieser E-Mail-Adresse oder Benutzernamen existiert bereits.';
export const REGISTER_INFO_INVALID = 'Benutzername, E-Mail und Password werden benötigt.';
export const ERROR_WHILE_REGISTER_USER = 'Fehler bei der Registrierung.';
export const INVALID_TOKEN = 'Deine Sitzung ist abgelaufen, bitte melde dich erneut an.';
export const TOKEN_REQUIRED = 'Du musst dich zuerst einloggen.';
export const ERROR_WHILE_CREATING_ROOM = 'Interner Fehler beim Anlegen des Raums.';
export const USER_NAME_OR_PW_NOT_EXISTS = 'Diese Kombination aus Benutzer & Passwort existiert nicht.';
export const LOCKING_DOCUMENT_CHANGED = 'Speichern nicht möglich. Das Dokument wurde zwischenzeitlich geändert.';
export const CREATE_ROOM_ERROR = 'Fehler beim Erstellen eines Raums.';
export const SAVE_RESTORE_ERROR = 'Fehler beim wiederherstellen des Dokuments.';
export const DELETE_ROOM_ERROR = 'Fehler beim Löschen des Raums.';
export const DELETE_USER_ERROR = 'Fehler beim Löschen des Benutzers.';
export const ROOM_DOES_NOT_EXIST = 'Der Raum existiert nicht mehr.';
export const DOCUMENT_TO_BE_RESTORED_NOT_EXIST = 'Das Dokument, dass du restoren wolltest konnte nicht gefunden werden.';
export const ROOM_TO_BE_STORED_NOT_EXIST = 'Der Raum an dem Du Anpassungen speichern wolltest existiert nicht mehr.';
export const ERROR_ON_DOCUMENT_SEARCH = 'Fehler bei der Dokumentensuche.';
export const USER_TO_DELETE_NOT_EXISTS = 'Der zu löschende User existiert nicht.';
export const ERROR_WHILE_TAGS_REQUEST = 'Fehler beim ermitteln von Tags.';
export const ERROR_WHILE_USERS_REQUEST = 'Fehler beim ermitteln der Benutzer.';
export const ERROR_WHILE_DOCUMENT_RELOAD = 'Fehler beim aktualisieren des Dokuments.';
export const ERROR_REGISTER_LINK_NO_LONGER_VALID = 'Leider ist dieser Registrierungslink nicht mehr gültig.';
export const ERROR_REGISTER_EMAIL_NO_MATCH = 'Leider stimmt diese E-Mail-Adresse nicht mit der E-Mail-Adresse für die er Link erstellt wurde überein.';
export const ERROR_WHILE_DOWNLOADING_IMAGE = 'Fehler beim Herunterladen der Bilddatei.';
export const ERROR_WHILE_SAVING_IMAGE = 'Fehler beim Speichern der Bilddatei.';
export const ERROR_NO_DOCUMENT_HISTORY_NOT_FOUND = 'Keine Dokumenthistorie gefunden.';
export const ERROR_NO_DOCUMENT_HISTORY_REQUEST = 'Fehler beim Abfragen der Dokumenthistorie.';
export const ERROR_REFESHING_TOKEN = 'Fehler beim Aktualisieren der Authentifizerung.';
export const ERROR_USER_IS_NOT_ADMIN = 'Du hast keine Admin Berechtigung.';export const ERROR_WHILE_DELETE_DOCUMENT = 'Fehler bei Löschen des Dokuments.';
export const ERROR_WHILE_CREATE_DOCUMENT = 'Fehler beim Anlegen des Dokuments.';
export const ERROR_WHILE_UPDATING_DOCUMENT = 'Fehler beim Speichern des Dokuments.';
export const ERROR_WHILE_RESTORING_DOCUMENT = 'Fehler beim Wiederherstellen des Dokuments.';
export const ERROR_WHILE_GETTING_DOCUMENT_EDITORS = 'Fehler beim Ermitteln der Bearbeiter dieses Dokuments.';
export const ERROR_FORMAT_DOCUMENT_EDITORS = 'Fehlerhafte Anfrage zum Ermitteln der Bearbeiter dieses Dokuments';
export const ERROR_WHILE_UPDATING_DOCUMENT_EDITORS = 'Fehler beim Speichern der Bearbeiter dieses Dokuments.';
export const ERROR_FORMAT_UPDATING_DOCUMENT_EDITORS = 'Benutzer können gespeichert werden, wenn das Dokument anleget wurde.';
export const ERROR_NOT_FOUND_DOCUMENT_EDITORS = 'Es können keine Bearbeiter für dieses Dokument gefunden werden.';
export const ERROR_DOCUMENT_NOT_FOUND_BY_ID = (faultyDocumentId: string) =>  `Ein Dokument mit der ID ${faultyDocumentId} konnte nicht gefunden werden`;
export const ERROR_GETTING_DOCUMENT = `Beim Abfragen des Dokuments kam es zu einem Fehler.`;

